volumes:
  public:
  data:
  postgres:
  redis:

networks:
  data:
  pretalx-web:
    external: true

x-default: &default
  networks:
    - data
    - pretalx-web
  restart: unless-stopped

x-healthcheck: &healthcheck
  start_period: 10s
  interval: 30s
  retries: 5
  timeout: 3s

x-pretalx: &pretalx
  <<: *default
  image: ghcr.io/tripleight/pretalx-extended:2024.3.0-cron
  volumes:
    - data:/data
    - public:/public
  env_file:
    - stack.env
  environment:
    - PRETALX_LOG_LEVEL
    - PRETALX_DB_NAME
    - PRETALX_DB_USER
    - PRETALX_DB_PASS
    - PRETALX_DATA_DIR
    - PRETALX_FILESYSTEM_LOGS
    - PRETALX_FILESYSTEM_MEDIA
    - PRETALX_FILESYSTEM_STATIC
    - PRETALX_DEBUG
    - PRETALX_SITE_URL
    - PRETALX_SITE_CSP
    - PRETALX_SITE_CSP_STYLE
    - PRETALX_SITE_CSP_SCRIPT
    - PRETALX_SITE_CSP_IMG
    - PRETALX_SITE_CSP_FORM
    - PRETALX_DB_TYPE
    - PRETALX_DB_HOST
    - PRETALX_DB_PORT
    - PRETALX_MAIL_FROM
    - PRETALX_MAIL_HOST
    - PRETALX_MAIL_PORT
    - PRETALX_MAIL_USER
    - PRETALX_MAIL_PASSWORD
    - PRETALX_MAIL_TLS
    - PRETALX_MAIL_SSL
    - PRETALX_CELERY_BACKEND
    - PRETALX_CELERY_BROKER
    - PRETALX_REDIS
    - PRETALX_REDIS_SESSIONS
    - PRETALX_LOGGING_EMAIL
    - PRETALX_LOGGING_EMAIL_LEVEL
    - PRETALX_LANGUAGE_CODE
    - PRETALX_TIME_ZONE

x-pretalx-depends-on-databases: &pretalx-depends-on-databases
  redis:
    condition: service_healthy
  postgres:
    condition: service_healthy

x-pretalx-depends-on-migrations: &pretalx-depends-on-migrations
  <<: *pretalx-depends-on-databases
  migrations:
    condition: service_completed_successfully


services:

  traefik:
    <<: *default
    image: traefik:v3.3.4
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/portainer/pretalx/traefik/configs/traefik.yml:/etc/traefik/traefik.yml:ro
      - /etc/portainer/pretalx/traefik/configs/config.yml:/etc/traefik/config.yml:ro
      - /etc/portainer/pretalx/traefik/cert/acme.json:/etc/traefik/acme.json
    env_file:
      - stack.env
    deploy:
      replicas: 1

  web:
    <<: *default
    image: nginx:alpine
    volumes:
      - public:/public
      - /etc/portainer/pretalx/traefik/configs/nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      traefik.enable: true
      traefik.http.routers.local-localhost.rule: Host(`${FQDN}`)
      traefik.http.routers.local-localhost.tls: true
      traefik.http.routers.local-localhost.tls.certresolver: letsencrypt
    
    deploy:
      replicas: 1

    healthcheck:
      test: ['CMD-SHELL', 'ash -c "[[ $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:80) == \"200\" ]]" || exit 1']
      <<: *healthcheck

    depends_on:
      app:
        condition: service_healthy


  app:
    <<: *pretalx
    command: gunicorn

    deploy:
      replicas: 1

    healthcheck:
      test: ['CMD-SHELL', 'bash -c "[[ $(curl -s -o /dev/null -w \"%{http_code}\" http://localhost:8080) == \"200\" ]]" || exit 1']
      <<: *healthcheck

    depends_on: *pretalx-depends-on-migrations

  worker:
    <<: *pretalx
    command: celery

    deploy:
      replicas: 1

    healthcheck:
      test: ['CMD-SHELL', 'bash -c "[[ \"$(pgrep celery)\" != \"\" ]]" || exit 1']
      <<: *healthcheck

    depends_on: *pretalx-depends-on-migrations

  cron:
    <<: *pretalx
    command: cron
    user: root
    init: true

    healthcheck:
      test: ['CMD-SHELL', 'bash -c "[[ \"$(pgrep cron)\" != \"\" ]]" || exit 1']
      <<: *healthcheck

    depends_on: *pretalx-depends-on-migrations

  migrations:
    <<: *pretalx
    command: migrate
    restart: no

    depends_on: *pretalx-depends-on-databases


  postgres:
    <<: *default
    image: docker.io/library/postgres:15-alpine
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - stack.env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  redis:
    <<: *default
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      <<: *healthcheck
    volumes:
      - redis:/data
