# traefik configuration

http:
  middlewares:
    secureHeaders:
      headers:
        customRequestHeaders:
          X-Content-Type-Options: nosniff
          Referrer-Policy: same-origin
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=()"
    rateLimit:
      rateLimit:
        average: 100
        burst: 50
    compression:
      compress:
        excludedContentTypes:
          - image/png
          - image/jpeg
          - image/gif
          - image/webp
          - image/x-icon
          - font/woff2
          - font/woff
    static-headers:
      headers:
        customResponseHeaders:
          Cache-Control: "public,max-age=31536000"
          X-Content-Type-Options: "nosniff"
        accessControlAllowMethods:
          - GET
          - OPTIONS
        accessControlMaxAge: 100
