http:
  routers:
    dashboard:
      rule: "Host(`traefik.${FQDN}`)"
      service: "api@internal"
      entryPoints:
        - websecure
      middlewares:
        - authtraefik
        - secure-headers

  middlewares:
    secure-headers:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    authtraefik:
      basicAuth:
        removeheader: true
        realm: "traefik-dashboard"
        users:
          - ${TRAEFIK_AUTH}
