networks:
  web:
    # Traefik is running in the same network as the app
    # this network might be started before the app network
    # so we need to explicitly set external: true
    external: true

services:
  web:
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.http.routers.pretalx.rule: Host(`${FQDN}`)
      traefik.http.routers.pretalx.entrypoints: websecure
      traefik.http.routers.pretalx.tls: true
      traefik.http.routers.pretalx.tls.certresolver: letsencrypt
      traefik.http.services.pretalx.loadbalancer.server.port: 80

  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--entrypoints.websecure.http.middlewares=secure-headers@file"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      # dashboard config
      - "--api.dashboard=true"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./compose/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro"
    labels:
      traefik.enable: true
      # dashboard config
      traefik.http.routers.dashboard.rule: Host(`traefik.${FQDN}`)
      traefik.http.routers.dashboard.service: api@internal
      traefik.http.routers.dashboard.middlewares: auth@file
      traefik.http.middlewares.auth.basicauth.users=pretalx:$apr1$dvz1EqdL$uZiKyRPAviG/FOPSK7LcB0
    environment:
      - TRAEFIK_AUTH
