networks:
  web:
    # Traefik is running in the same network as the app
    # this network might be started before the app network
    # so we need to explicitly set external: true
    external: true

services:
  web:
    networks:
      - web

  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ./letsencrypt:/letsencrypt
      - ./.env:/etc/traefik/.env
    command:
      - "--configfile=/etc/traefik/traefik_dynamic.yml"
